
package com.dbs.services.person;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-07-02T12:36:51.948+08:00
 * Generated source version: 3.1.10
 * 
 */
public final class PersonService_PersonServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.dbs.com/", "PersonServiceImplService");

    private PersonService_PersonServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PersonServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PersonServiceImplService ss = new PersonServiceImplService(wsdlURL, SERVICE_NAME);
        PersonService port = ss.getPersonServiceImplPort();  
        
        {
        System.out.println("Invoking getPerson...");
        java.util.List<com.dbs.services.person.Person> _getPerson__return = port.getPerson();
        System.out.println("getPerson.result=" + _getPerson__return);


        }

        System.exit(0);
    }

}
