package com.dbs.services.person;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-07-02T12:36:52.033+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "PersonServiceImplService", 
                  wsdlLocation = "http://localhost:8080/personService?wsdl",
                  targetNamespace = "http://services.dbs.com/") 
public class PersonServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.dbs.com/", "PersonServiceImplService");
    public final static QName PersonServiceImplPort = new QName("http://services.dbs.com/", "PersonServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/personService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PersonServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/personService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PersonServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PersonServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PersonServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PersonServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServiceImplPort")
    public PersonService getPersonServiceImplPort() {
        return super.getPort(PersonServiceImplPort, PersonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServiceImplPort")
    public PersonService getPersonServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PersonServiceImplPort, PersonService.class, features);
    }

}
