
package com.dbs.services.student;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-07-02T22:04:31.309+08:00
 * Generated source version: 3.1.10
 * 
 */
public final class StudentService_StudentServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://cxf.student.com/", "StudentServiceImplService");

    private StudentService_StudentServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = StudentServiceImplService.WSDL_LOCATION;
      
        StudentServiceImplService ss = new StudentServiceImplService(wsdlURL, SERVICE_NAME);
        StudentService port = ss.getStudentServiceImplPort();  
        
        {
        System.out.println("Invoking uploadFile...");
        System.out.println(new File("cxf-client/src/main/resources/helloService.wsdl").getAbsolutePath());

        com.dbs.services.student.UploadFile _uploadFile_parameters = new UploadFile();
        DataSource dataSource = new FileDataSource(new File("cxf-client/src/main/resources/helloService.wsdl"));
        DataHandler dataHandler = new DataHandler(dataSource);
        _uploadFile_parameters.setFileContent(dataHandler);
            com.dbs.services.student.UploadFileResponse _uploadFile__return = port.uploadFile(_uploadFile_parameters);
        System.out.println("uploadFile.result=" + _uploadFile__return);
        }

        {
        System.out.println("Invoking queryStudentById...");
        com.dbs.services.student.QueryStudentByIdRequest _queryStudentById_parameters = new QueryStudentByIdRequest();
        _queryStudentById_parameters.setName("Jack");
        com.dbs.services.student.Student _queryStudentById__return = port.queryStudentById(_queryStudentById_parameters);
        System.out.println("queryStudentById.result=" + _queryStudentById__return);


        }
        {
        System.out.println("Invoking queryStudentByAddress...");
        com.dbs.services.student.QueryStudentsByAddressRequest _queryStudentByAddress_parameters = new QueryStudentsByAddressRequest();
        _queryStudentByAddress_parameters.setName("NewYork");
        com.dbs.services.student.ListOfStudent _queryStudentByAddress__return = port.queryStudentByAddress(_queryStudentByAddress_parameters);
        System.out.println("queryStudentByAddress.result=" + _queryStudentByAddress__return.getStudents().size());


        }
        {
        System.out.println("Invoking queryRolesById...");
        com.dbs.services.student.QueryRolesByIdRequest _queryRolesById_parameters = new QueryRolesByIdRequest();
        _queryRolesById_parameters.setId(0);
        com.dbs.services.student.Role _queryRolesById__return = port.queryRolesById(_queryRolesById_parameters);
        System.out.println("queryRolesById.result=" + _queryRolesById__return);
        }

        System.exit(0);
    }

}
