package com.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-07-03T21:52:23.493+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "com.cxf.service", name = "HelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloService {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "com.cxf.service", className = "com.cxf.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "com.cxf.service", className = "com.cxf.client.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
