/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Yufeng' at '12/26/16 8:57 PM' with Gradle 3.2.1
 *
 * @author Yufeng, @date 12/26/16 8:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
