
package com.dbs.services.order;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-07-02T14:25:52.472+08:00
 * Generated source version: 3.1.10
 * 
 */
public final class OrderService_OrderServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://cxf.order.com/", "OrderServiceImplService");

    private OrderService_OrderServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OrderServiceImplService.WSDL_LOCATION;
        OrderServiceImplService ss = new OrderServiceImplService(wsdlURL, SERVICE_NAME);
        OrderService port = ss.getOrderServiceImplPort();  
        
        {
        System.out.println("Invoking queryByProductName...");
        com.dbs.services.order.QueryByProductName _queryByProductName_parameters = new QueryByProductName();
        _queryByProductName_parameters.setName("iPad");
        com.dbs.services.order.QueryByProductNameResponse _queryByProductName__return = port.queryByProductName(_queryByProductName_parameters);
        System.out.println("queryByProductName.result=" + _queryByProductName__return);


        }

        System.exit(0);
    }

}
