
package com.dbs.services.student;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-07-02T22:04:05.090+08:00
 * Generated source version: 3.1.10
 * 
 */
 
public class StudentService_StudentServiceImplPort_Server{

    protected StudentService_StudentServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new StudentServiceImplPortImpl();
        String address = "http://localhost:8080/studentService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new StudentService_StudentServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
