package com.dbs.services.student;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-07-02T22:04:05.090+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "StudentServiceImplService", 
                  wsdlLocation = "D:/Workspace/IDEA/webservices/cxf-server/src/main/resources/studentService.wsdl",
                  targetNamespace = "http://cxf.student.com/") 
public class StudentServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxf.student.com/", "StudentServiceImplService");
    public final static QName StudentServiceImplPort = new QName("http://cxf.student.com/", "StudentServiceImplPort");
    static {
        URL url = StudentServiceImplService.class.getResource("D:/Workspace/IDEA/webservices/cxf-server/src/main/resources/studentService.wsdl");
        if (url == null) {
            url = StudentServiceImplService.class.getClassLoader().getResource("D:/Workspace/IDEA/webservices/cxf-server/src/main/resources/studentService.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(StudentServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "D:/Workspace/IDEA/webservices/cxf-server/src/main/resources/studentService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public StudentServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public StudentServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StudentServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StudentServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns StudentService
     */
    @WebEndpoint(name = "StudentServiceImplPort")
    public StudentService getStudentServiceImplPort() {
        return super.getPort(StudentServiceImplPort, StudentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentService
     */
    @WebEndpoint(name = "StudentServiceImplPort")
    public StudentService getStudentServiceImplPort(WebServiceFeature... features) {
        return super.getPort(StudentServiceImplPort, StudentService.class, features);
    }

}
