
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.dbs.services.order;

import java.util.Date;
import java.util.UUID;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-07-02T14:03:38.925+08:00
 * Generated source version: 3.1.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderServiceImplService",
                      portName = "OrderServiceImplPort",
                      targetNamespace = "http://cxf.order.com/",
                      wsdlLocation = "D:/Workspace/IDEA/webservices/cxf-server/src/main/resources/orderService.wsdl",
                      endpointInterface = "com.dbs.services.order.OrderService")
                      
public class OrderServiceImplPortImpl implements OrderService {

    private static final Logger LOG = Logger.getLogger(OrderServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.dbs.services.order.OrderService#queryByProductName(com.dbs.services.order.QueryByProductName parameters)*
     */
    public com.dbs.services.order.QueryByProductNameResponse queryByProductName(QueryByProductName parameters) { 
        LOG.info("Executing operation queryByProductName");
        System.out.println(parameters);
        try {
            com.dbs.services.order.QueryByProductNameResponse _return = new QueryByProductNameResponse();
            _return.setId(UUID.randomUUID().variant());
            _return.setOrderName(parameters.getName());
            _return.setOwner("Yufeng");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
